In [1]:
import numpy as np

In [2]:
matriksA = np.array([[1,2],[1,6]])
print(matriksA)

[[1 2]
 [1 6]]


In [3]:
matriksB = np.array([[4,5],[2,7]])
print(matriksB)

[[4 5]
 [2 7]]


In [4]:
matriksC = matriksA + matriksB
print(matriksC)

[[ 5  7]
 [ 3 13]]


In [6]:
matriksD = matriksA - matriksB
print(matriksD)

[[-3 -3]
 [-1 -1]]


In [7]:
matriksE = np.dot(matriksA,matriksB)
print(matriksE)

[[ 8 19]
 [16 47]]


In [9]:
matriksF = np.linalg.det([[1,2],[3,2]])
print(matriksF)

-4.000000000000001


In [11]:
matriksG = np.array([[1,1,1],[2,1,1],[3,3,1]])
print(matriksG.transpose())

[[1 2 3]
 [1 1 3]
 [1 1 1]]
